### PR TITLE
feat add descriptors

### PR DESCRIPTION
**Pull request by Symbitic**
I think I finally got descriptors working!

I tested on Windows and it works.
It should work on Linux (will test shortly).
I have no access to macOS, so while I *think* it will work, I have no idea.

I changed the Findsimplebluez.cmake to checkout the 'next' branch (since I need the descriptor code, obviously). You can change that back as soon as the next SimpleBluez is released.

### CODE REVIEW

**Comment by kdewald** [comment]
Hey, this is great! I'll prioritize merging this first, I'll then add my stack of changes on top, as they seem complementary.

**Comment by Symbitic** [comment]
I *think* I got the macOS fixed, and I fixed the Bluez typo and ran clang-format.

**Comment by Symbitic** [comment]
macOS fix: take 2. compare isNotEqual using CBUUID.

**Comment by kdewald** [comment]
Hey @Symbitic, your contributions have been really helpful in speeding this process up! I've ported most of your changes into https://github.com/OpenBluetoothToolbox/SimpleBLE/pull/81 (adapting the fixes I had made before), so I think we're almost there to test this out and get it landed.

**Comment by kdewald** [comment]
Hey @Symbitic, I've ported your changes into my MR and everything is now landed on `main`. There are a few naming conventions that are different, but the same logic is there for testing. I'll proceed with further testing and stability improvements in the upcoming days.

Thanks again for the help! This made the process super quick.

**Pull request merged**
